CREATE DATABASE DECOAPP;
USE DECOAPP;

CREATE TABLE Clientes (
Id INT NOT NULL PRIMARY KEY identity(1,1),
Nombre VARCHAR(50) NOT NULL,
DNI VARCHAR(15) NOT NULL,
Telefono VARCHAR(12) NOT NULL,
Direccion VARCHAR(40) NULL,
Email VARCHAR(20) NULL,
Poblacion VARCHAR(20) NULL,
Ciudad VARCHAR(20) NOT NULL,
CP VARCHAR(5) NOT NULL
);
CREATE TABLE Empresa (
Id INT NOT NULL PRIMARY KEY identity(1,1),
Nombre VARCHAR(50) NOT NULL,
CIF VARCHAR(15) NOT NULL,
Telefono VARCHAR(12) NOT NULL,
Direccion VARCHAR(40) NULL,
Email VARCHAR(20) NULL,
Poblacion VARCHAR(20) NULL,
Ciudad VARCHAR(20) NOT NULL,
CP VARCHAR(5) NOT NULL
);


CREATE TABLE Estado (
Id INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(20) NOT NULL
);

CREATE TABLE Citas (
Id INT NOT NULL PRIMARY KEY identity(1,1),
Fecha DATETIME NOT NULL,
Hora TIME NULL,
Comentario VARCHAR(50) NULL,
IdCliente Int FOREIGN KEY REFERENCES Clientes(Id) NULL,
);

CREATE TABLE Facturas (
Id INT NOT NULL PRIMARY KEY identity(1,1),
NombreFactura VARCHAR(30) NOT NULL,
IdCliente Int FOREIGN KEY REFERENCES Clientes(Id) NULL,
Fecha DATETIME NOT NULL,
IVA INT NULL,
IdEstado INT NOT NULL FOREIGN KEY REFERENCES Estado(Id),
IdEmpresa INT NOT NULL FOREIGN KEY REFERENCES Empresa(Id)
);

CREATE TABLE Tareas (
Id INT NOT NULL PRIMARY KEY identity(1,1),
Descripcion VARCHAR(50) NOT NULL,
Cantidad INT  NULL,
Descuento INT NULL,
Precio INT NULL,
IdFactura Int NOT NULL FOREIGN KEY REFERENCES Facturas(Id),
IdEstado INT NULL FOREIGN KEY REFERENCES Estado(Id)
);

CREATE TABLE Materiales (
Id INT NOT NULL PRIMARY KEY identity(1,1),
Nombre VARCHAR(20) NOT NULL,
Cantidad INT NULL,
Precio DECIMAL NULL,
IdFactura Int NULL FOREIGN KEY REFERENCES Facturas(Id),

);

CREATE TABLE Users (
Id INT NOT NULL PRIMARY KEY identity(1,1),
Nombre VARCHAR(20) NOT NULL,
UserName VARCHAR(20) NOT NULL,
Password VARCHAR(20) NOT NULL
);

CREATE TABLE Obras (
Id INT NOT NULL PRIMARY KEY identity(1,1),
Direccion VARCHAR(40) NOT NULL,
IdCliente Int  NULL FOREIGN KEY REFERENCES Clientes(Id),
CP	VARCHAR(5) NOT NULL,
FechaInicio DATETIME NOT NULL,
FechaFinal DATETIME,
IdEstado INT NOT NULL FOREIGN KEY REFERENCES Estado(Id),
IdFactura Int NULL FOREIGN KEY REFERENCES Facturas(Id),
IdEmpresa INT NOT NULL FOREIGN KEY REFERENCES Empresa(Id)
);

CREATE TABLE Trabajadores (
Id INT NOT NULL PRIMARY KEY identity(1,1),
Nombre VARCHAR(20) NOT NULL,
DNI VARCHAR(15) NOT NULL,
Telefono VARCHAR(12) NOT NULL,
Direccion VARCHAR(40),
Email VARCHAR(20),
ObraActiva Int FOREIGN KEY REFERENCES Obras(Id) null,
);


